-- Streamverse PostgreSQL schema (migrated from Oracle DDL.txt)

CREATE TABLE user_netflix (
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    dob TIMESTAMP NOT NULL,
    country CHAR(30) NOT NULL,
    credit_card VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL,
    phone VARCHAR(50),
    joined TIMESTAMP DEFAULT NOW(),
    max_profiles INTEGER DEFAULT 0,
    CONSTRAINT user_pk PRIMARY KEY (email)
);

CREATE TABLE profile (
    profile_id VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    dob TIMESTAMP NOT NULL,
    CONSTRAINT profile_pk PRIMARY KEY (email, profile_id),
    CONSTRAINT user_fk FOREIGN KEY (email) REFERENCES user_netflix (email) ON DELETE CASCADE
);

CREATE TABLE subscription (
    sub_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    sub_type VARCHAR(10) NOT NULL,
    email VARCHAR(100),
    start_date TIMESTAMP DEFAULT NOW(),
    end_date TIMESTAMP NOT NULL,
    bill NUMERIC(10, 2) DEFAULT 0.0,
    total_bill NUMERIC(10, 2) DEFAULT 0,
    running INTEGER,
    termination_date TIMESTAMP,
    CONSTRAINT sub_pk PRIMARY KEY (sub_id, email),
    CONSTRAINT sub_fk FOREIGN KEY (email) REFERENCES user_netflix (email) ON DELETE CASCADE
);

CREATE TABLE movie (
    movie_id INTEGER PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    country CHAR(30),
    rating NUMERIC(4, 2) DEFAULT 0.0,
    total_views INTEGER DEFAULT 0,
    total_votes INTEGER DEFAULT 0,
    description VARCHAR(1000),
    image_url VARCHAR(200),
    video_url VARCHAR(200),
    length NUMERIC(5, 2) DEFAULT 0.0,
    language VARCHAR(10),
    price NUMERIC(4, 2) DEFAULT 0.0,
    maturity_rating VARCHAR(30),
    release_date TIMESTAMP NOT NULL
);

CREATE TABLE show (
    show_id INTEGER PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    country CHAR(30),
    rating NUMERIC(4, 2) DEFAULT 0.0,
    total_views INTEGER DEFAULT 0,
    total_votes INTEGER DEFAULT 0,
    description VARCHAR(1000),
    image_url VARCHAR(200),
    video_url VARCHAR(200),
    length NUMERIC(5, 2) DEFAULT 0.0,
    language VARCHAR(10),
    seasons INTEGER DEFAULT 0,
    episodes INTEGER DEFAULT 0,
    price NUMERIC DEFAULT 0.0,
    maturity_rating VARCHAR(30)
);

CREATE TABLE celeb (
    celeb_id INTEGER PRIMARY KEY,
    name VARCHAR(30),
    contents INTEGER DEFAULT 0
);

CREATE TABLE genre (
    genre_id INTEGER PRIMARY KEY,
    name VARCHAR(30),
    contents INTEGER DEFAULT 0
);

CREATE TABLE episode (
    season_no INTEGER NOT NULL,
    episode_no INTEGER NOT NULL,
    show_id INTEGER NOT NULL,
    title VARCHAR(30),
    description VARCHAR(200),
    length NUMERIC(5, 2),
    image_url VARCHAR(200),
    video_url VARCHAR(200),
    CONSTRAINT episode_pk PRIMARY KEY (season_no, episode_no, show_id),
    CONSTRAINT episode_fk FOREIGN KEY (show_id) REFERENCES show (show_id)
);

CREATE TABLE movie_watch (
    movie_id INTEGER NOT NULL,
    profile_id VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    rating INTEGER,
    watched_upto NUMERIC DEFAULT 0,
    time TIMESTAMP DEFAULT NOW(),
    CONSTRAINT movie_watch_pk PRIMARY KEY (movie_id, email, profile_id),
    CONSTRAINT movie_watch_fk1 FOREIGN KEY (movie_id) REFERENCES movie (movie_id),
    CONSTRAINT movie_watch_fk2 FOREIGN KEY (profile_id, email) REFERENCES profile (profile_id, email)
);

CREATE TABLE movie_watchlist (
    movie_id INTEGER NOT NULL,
    email VARCHAR(100) NOT NULL,
    profile_id VARCHAR(30) NOT NULL,
    CONSTRAINT movie_watchlist_pk PRIMARY KEY (movie_id, profile_id, email),
    CONSTRAINT movie_watchlist_fk1 FOREIGN KEY (movie_id) REFERENCES movie (movie_id),
    CONSTRAINT movie_watchlist_fk2 FOREIGN KEY (profile_id, email) REFERENCES profile (profile_id, email)
);

CREATE TABLE movie_genre (
    movie_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT movie_genre_pk PRIMARY KEY (movie_id, genre_id),
    CONSTRAINT movie_genre_fk1 FOREIGN KEY (movie_id) REFERENCES movie (movie_id),
    CONSTRAINT movie_genre_fk2 FOREIGN KEY (genre_id) REFERENCES genre (genre_id)
);

CREATE TABLE movie_similarity (
    movie_id1 INTEGER NOT NULL,
    movie_id2 INTEGER NOT NULL,
    score NUMERIC(4, 2),
    CONSTRAINT movie_similarity_pk PRIMARY KEY (movie_id1, movie_id2),
    CONSTRAINT movie_similarity_fk1 FOREIGN KEY (movie_id1) REFERENCES movie (movie_id),
    CONSTRAINT movie_similarity_fk2 FOREIGN KEY (movie_id2) REFERENCES movie (movie_id)
);

CREATE TABLE movie_celeb (
    movie_id INTEGER NOT NULL,
    celeb_id INTEGER NOT NULL,
    role VARCHAR(15),
    CONSTRAINT movie_celeb_pk PRIMARY KEY (movie_id, celeb_id),
    CONSTRAINT movie_celeb_fk1 FOREIGN KEY (movie_id) REFERENCES movie (movie_id),
    CONSTRAINT movie_celeb_fk2 FOREIGN KEY (celeb_id) REFERENCES celeb (celeb_id)
);

CREATE TABLE show_watch (
    profile_id VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    show_id INTEGER NOT NULL,
    rating INTEGER,
    status VARCHAR(10),
    watched_upto NUMERIC,
    time TIMESTAMP DEFAULT NOW(),
    CONSTRAINT show_watch_pk PRIMARY KEY (profile_id, show_id, email),
    CONSTRAINT show_watch_fk1 FOREIGN KEY (profile_id, email) REFERENCES profile (profile_id, email),
    CONSTRAINT show_watch_fk2 FOREIGN KEY (show_id) REFERENCES show (show_id)
);

CREATE TABLE show_watchlist (
    profile_id VARCHAR(30) NOT NULL,
    show_id INTEGER NOT NULL,
    email VARCHAR(100) NOT NULL,
    CONSTRAINT show_watchlist_pk PRIMARY KEY (show_id, profile_id, email),
    CONSTRAINT show_watchlist_fk1 FOREIGN KEY (profile_id, email) REFERENCES profile (profile_id, email),
    CONSTRAINT show_watchlist_fk2 FOREIGN KEY (show_id) REFERENCES show (show_id)
);

CREATE TABLE show_similarity (
    show_id1 INTEGER NOT NULL,
    show_id2 INTEGER NOT NULL,
    score NUMERIC(4, 2),
    CONSTRAINT show_similarity_pk PRIMARY KEY (show_id1, show_id2),
    CONSTRAINT show_similarity_fk1 FOREIGN KEY (show_id1) REFERENCES show (show_id),
    CONSTRAINT show_similarity_fk2 FOREIGN KEY (show_id2) REFERENCES show (show_id)
);

CREATE TABLE episode_watch (
    profile_id VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL,
    season_no INTEGER NOT NULL,
    episode_no INTEGER NOT NULL,
    show_id INTEGER NOT NULL,
    status VARCHAR(10),
    watched_upto NUMERIC DEFAULT 0,
    time TIMESTAMP DEFAULT NOW(),
    CONSTRAINT episode_watch_pk PRIMARY KEY (profile_id, season_no, show_id, episode_no, email),
    CONSTRAINT episode_watch_fk1 FOREIGN KEY (profile_id, email) REFERENCES profile (profile_id, email),
    CONSTRAINT episode_watch_fk2 FOREIGN KEY (season_no, episode_no, show_id) REFERENCES episode (season_no, episode_no, show_id)
);

CREATE TABLE show_genre (
    show_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT show_genre_pk PRIMARY KEY (show_id, genre_id),
    CONSTRAINT show_genre_fk1 FOREIGN KEY (show_id) REFERENCES show (show_id),
    CONSTRAINT show_genre_fk2 FOREIGN KEY (genre_id) REFERENCES genre (genre_id)
);

CREATE TABLE show_celeb (
    show_id INTEGER NOT NULL,
    celeb_id INTEGER NOT NULL,
    role VARCHAR(20),
    CONSTRAINT show_celeb_pk PRIMARY KEY (show_id, celeb_id),
    CONSTRAINT show_celeb_fk1 FOREIGN KEY (show_id) REFERENCES show (show_id),
    CONSTRAINT show_celeb_fk2 FOREIGN KEY (celeb_id) REFERENCES celeb (celeb_id)
);

CREATE TABLE subscription_type (
    sub_type VARCHAR(10) PRIMARY KEY,
    bill NUMERIC(10, 2),
    num_profiles INTEGER
);

INSERT INTO subscription_type (sub_type, bill, num_profiles) VALUES
    ('BASIC', 5, 2),
    ('STANDARD', 8, 4),
    ('PREMIUM', 10, 6);
